import UIKit

/// A protocol for implementing a view that is available on the views library. Contains information about the type of view, implements preview and a configuration when the view is placed.
public protocol InterfaceBuilderView {
    
    /// The type of view.
    var type: UIView.Type { get }
    
    /// If a color is returned, a square with that color will be shown as preview on the library.
    var previewColor: UIColor? { get }
    
    /// If `previewColor` is not set, called for configuring `view` for preview.
    ///
    /// - Parameters:
    ///     - view: View shown as preview.
    func preview(view: UIView)
    
    /// Called to configure `view` when it's dropped.
    ///
    /// - Parameters:
    ///     - view: View generated by the library.
    func configure(view: UIView)
}

/*extension InterfaceBuilderView {
    
    public func preview(view: UIView) {}
    public var previewColor: UIColor? { return nil }
}*/
